version: '3.9'
services:
  database:
    image: postgres:latest
    container_name: task_manager_bd
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task_manager_network

  minio:
    image: minio/minio:latest
    container_name: task_manager_minio
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - task_manager_network

networks:
  task_manager_network:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
